routes/web.php
<?php

Route::name('index')->get('/', 'HomeController@index');
Route::name('terms')->get('/terms', 'HomeController@terms');
Route::name('contact')->post('contact', 'ContactController@store');
Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
Auth::routes(['register' => false]);

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@panel')->name('panel');

    Route::prefix('home')->name('home.')->group(function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('create', 'AdminController@create')->name('create');
        Route::post('create', 'AdminController@store')->name('store');
        Route::post('{id}/delete', 'AdminController@destroy')->name('destroy');
        Route::get('{id}', 'AdminController@show')->name('show');
        Route::post('{id}', 'AdminController@update')->name('update');
    });

    Route::prefix('home2')->name('home2.')->group(function () {
        Route::get('/', 'HomeController@admin')->name('index');
        Route::get('create', 'HomeController@create')->name('create');
        Route::post('create', 'HomeController@store')->name('store');
        Route::post('{id}/delete', 'HomeController@destroy')->name('destroy');
        Route::get('{id}', 'HomeController@show')->name('show');
        Route::post('{id}', 'HomeController@update')->name('update');

        Route::get('{home}/photos/', 'HomePhotoController@index')->name('photo.index');
        Route::get('{home}/photos/create', 'HomePhotoController@create')->name('photo.create');
        Route::post('{home}/photos/create', 'HomePhotoController@store')->name('photo.store');
        Route::post('{home}/photos/{id}/delete', 'HomePhotoController@destroy')->name('photo.destroy');
        Route::get('{home}/photos/{id}', 'HomePhotoController@show')->name('photo.show');
        Route::post('{home}/photos/{id}', 'HomePhotoController@update')->name('photo.update');
    });

    Route::prefix('obras')->name('cons.')->group(function () {
        Route::get('/', 'ConsController@index')->name('index');
        Route::get('create', 'ConsController@create')->name('create');
        Route::post('create', 'ConsController@store')->name('store');
        Route::post('{id}/delete', 'ConsController@destroy')->name('destroy');
        Route::get('{id}', 'ConsController@show')->name('show');
        Route::post('{id}', 'ConsController@update')->name('update');
        Route::get('{month}/{year}', 'ConsController@folder')->name('folder');
    });

    Route::prefix('contatos')->name('contact.')->group(function () {
        Route::get('/', 'ContactController@index')->name('index');
    });

    Route::prefix('fale-conosco')->name('support.')->group(function () {
        Route::get('/{pp?}', 'SupportController@show')->name('show');
        Route::post('/', 'SupportController@update')->name('update');
    });

});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Construction;
use App\Models\Home1;
use App\Models\Home2;
use App\Models\Support;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    protected $home;

    public function __construct(Home2 $home) {
        $this->middleware('auth')->except(['index', 'terms']);
        $this->home = $home;
    }

    public function admin()
    {
        $data = $this->home->paginate();

        return view('admin.home2.index', compact('data'));
    }

    public function create()
    {
        return view('admin.home2.create');
    }

    public function store(Request $request)
    {
        $input = $request->all();

        $input['img'] = $this->img($input, 'img', 'home');
        if (isset($input['background'])) {
            $input['background'] = $this->img($input, 'background', 'home');
        }
        $this->home->create($input);

        toastr()->success('Cadastrado com sucesso!');

        return redirect()->route('adm.home2.index');
    }

    public function show($id)
    {
        $data = $this->home->find($id);

        return view('admin.home2.edit', compact('data'));
    }

    public function update($id, Request $request)
    {
        $input = $request->all();
        if (isset($input['img'])) {
            $input['img'] = $this->img($input, 'img', 'home');
        } else {
            unset($input['img']);
        }
        if (isset($input['background'])) {
            $input['background'] = $this->img($input, 'background', 'home');
        } else {
            unset($input['background']);
        }
        $this->home->find($id)->update($input);

        toastr()->success('Atualizado com sucesso!');

        return redirect()->route('adm.home2.index');
    }

    public function destroy($id)
    {
        $this->home->find($id)->delete();

        toastr()->success('Apagado com sucesso!');

        return redirect()->route('adm.home2.index');
    }

    public function index(Request $request)
    {
        $home1 = Home1::orderBy('id', 'DESC')->get()->groupBy('type');
        
        $home2 = $this->home->with('photos')->get()->toArray();
        
        $cons['years'] = Construction::all()->pluck('year', 'year')->toArray();
        $cons['months'] = Construction::all()->pluck('month_txt', 'month')->toArray();
        $first = Construction::latest()->first();
        $cons['default'] = $first ? $first->toArray() : ['year' => 1, 'month' => 0];
        $support = Support::find(1);
        
        return view('index', compact('home1', 'home2', 'cons', 'support'));
    }
    public function terms(Request $request)
    {
        $support = Support::find(1);

        return view('terms', compact('support'));
    }
}

resources/views/admin/home/_form.blade.php
@php
  $file = isset($data) ? [] : ['required'];
@endphp
<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('name', 'Título', ['class' => '']) !!}
    {!! Form::text('name', old('name'), ['class' => 'form-control', 'required']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('type', 'Tipo', ['class' => '']) !!}
    {!! Form::text('type', old('type'), ['class' => 'form-control', 'required']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('url', '360', ['class' => '']) !!}<br>
    {!! Form::text('url', old('url'), ['class' => 'form-control', 'required']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('img', 'Thumb', ['class' => '']) !!} <br>
    @if(isset($data) && $data->img) <img src="{{url('storage/home/'.$data->img)}}" width="50px" height="30px" style="margin-bottom: 5px;"> @endif
    {!! Form::file('img', false) !!}
  </div>
</div>

resources/views/admin/home/create.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::open(['method' => 'POST', 'role' => 'form', 'class' => 'form', 'route' => 'adm.home.store', 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Novo Post</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados pessoais
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.home._form')

              <a href="{{ route('adm.home.index') }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/home/edit.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::model($data, ['method' => 'POST', 'role' => 'form', 'class' => 'form', 'route' => ['adm.home.update', $data->id], 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Editar Post</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados pessoais
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.home._form')

              <a href="{{ route('adm.home.index') }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/home/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Home</h1>
      <div class="section-header-button mr-2">
        <a href="{{ route('adm.home.create') }}" class="btn btn-success btn-icon btn-lg btn-success" title="Adicionar"> <i class="fas fa-plus"></i> Adicionar</a>
      </div>
  </div>

  <div class="section-body">
    <div class="row mt-4">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>
              <i class="far fa-user lga"></i>
              Listagem <br>
              <small>{{ $data->total() }} resultados.</small>
            </h4>
          </div>
          <div class="card-body -table">
            <div class="table-responsive">
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Tipo</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($data as $d)
                    <tr>
                      <td>{{ $d->id }}</td>
                      <td>{{ $d->name }}</td>
                      <td>{{ $d->type }}</td>
                      <!--<td>@if($d->img) <img src="storage/home/'.$d->img)" width="50px" style="margin-bottom: 5px;"> @endif</td>-->
                      {!! Form::open(['route' => ['adm.home.destroy', $d->id]]) !!}
                      <td class="no-wrap">
                        <a href="{{ route('adm.home.show', $d->id) }}" class="btn btn-success">Editar</a> | 
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Essa ação não pode ser desfeita!')">Apagar</button>
                      </td>
                      {!! Form::close() !!}
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer">
            <div class="float-right">
              <nav>
                {!! $data->render() !!}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection