routes/web.php
<?php

Route::name('index')->get('/', 'HomeController@index');
Route::name('terms')->get('/terms', 'HomeController@terms');
Route::name('contact')->post('contact', 'ContactController@store');
Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
Auth::routes(['register' => false]);

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@panel')->name('panel');

    Route::prefix('home')->name('home.')->group(function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('create', 'AdminController@create')->name('create');
        Route::post('create', 'AdminController@store')->name('store');
        Route::post('{id}/delete', 'AdminController@destroy')->name('destroy');
        Route::get('{id}', 'AdminController@show')->name('show');
        Route::post('{id}', 'AdminController@update')->name('update');
    });

    Route::prefix('home2')->name('home2.')->group(function () {
        Route::get('/', 'HomeController@admin')->name('index');
        Route::get('create', 'HomeController@create')->name('create');
        Route::post('create', 'HomeController@store')->name('store');
        Route::post('{id}/delete', 'HomeController@destroy')->name('destroy');
        Route::get('{id}', 'HomeController@show')->name('show');
        Route::post('{id}', 'HomeController@update')->name('update');

        Route::get('{home}/photos/', 'HomePhotoController@index')->name('photo.index');
        Route::get('{home}/photos/create', 'HomePhotoController@create')->name('photo.create');
        Route::post('{home}/photos/create', 'HomePhotoController@store')->name('photo.store');
        Route::post('{home}/photos/{id}/delete', 'HomePhotoController@destroy')->name('photo.destroy');
        Route::get('{home}/photos/{id}', 'HomePhotoController@show')->name('photo.show');
        Route::post('{home}/photos/{id}', 'HomePhotoController@update')->name('photo.update');
    });

    Route::prefix('obras')->name('cons.')->group(function () {
        Route::get('/', 'ConsController@index')->name('index');
        Route::get('create', 'ConsController@create')->name('create');
        Route::post('create', 'ConsController@store')->name('store');
        Route::post('{id}/delete', 'ConsController@destroy')->name('destroy');
        Route::get('{id}', 'ConsController@show')->name('show');
        Route::post('{id}', 'ConsController@update')->name('update');
        Route::get('{month}/{year}', 'ConsController@folder')->name('folder');
    });

    Route::prefix('contatos')->name('contact.')->group(function () {
        Route::get('/', 'ContactController@index')->name('index');
    });

    Route::prefix('fale-conosco')->name('support.')->group(function () {
        Route::get('/{pp?}', 'SupportController@show')->name('show');
        Route::post('/', 'SupportController@update')->name('update');
    });

});

app/Models/Construction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Construction extends Model
{
    protected $fillable = [
        'year', 'month', 'img', 'title'
    ];

    protected $appends = ['url'];

    public function getUrlAttribute()
    {
      return url('storage/cons/'.$this->img);
    }

    public function getMonthTxtAttribute()
    {
        $arr = [
          '01' => 'JAN',
          '02' => 'FEV',
          '03' => 'MAR',
          '04' => 'ABR',
          '05' => 'MAI',
          '06' => 'JUN',
          '07' => 'JUL',
          '08' => 'AGO',
          '09' => 'SET',
          '10' => 'OUT',
          '11' => 'NOV',
          '12' => 'DEZ',
        ];

        return $arr[$this->month];
    }
}

resources/views/admin/construction/_form.blade.php
@php $year = isset($data) ? $data->year : date('Y') @endphp
<div class="col-sm-12 col-md-2">
  <div class="form-group mb-2">
    {!! Form::label('year', 'Ano', ['class' => '']) !!}
    {!! Form::number('year', $year, ['class' => 'form-control required']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-2">
  <div class="form-group mb-2">
    {!! Form::label('month', 'Mês', ['class' => '']) !!}
    {!! Form::select('month', [
      '01' => 'Janeiro',
      '02' => 'Fevereiro',
      '03' => 'Março',
      '04' => 'Abril',
      '05' => 'Maio',
      '06' => 'Junho',
      '07' => 'Julho',
      '08' => 'Agosto',
      '09' => 'Setembro',
      '10' => 'Outubro',
      '11' => 'Novembro',
      '12' => 'Dezembro',
    ], old('month'), ['class' => 'form-control required']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-8">
  <div class="form-group mb-8">
    {!! Form::label('img', isset($data) ? 'Imagem' : 'Imagens', ['class' => '']) !!}<br>
    @if(isset($data) && $data->img) <img src="{{url('storage/cons/'.$data->img)}}" width="50px" height="30px" style="margin-bottom: 5px;"> @endif
    @if(isset($data))
      {!! Form::file('img') !!}
    @else
      <input multiple="multiple" name="imgs[]" type="file"> 
    @endif
  </div>
</div>

@if(isset($data))
<div class="col-sm-12 col-md-12">
  <div class="form-group mb-12">
    {!! Form::label('title', 'Descrição', ['class' => '']) !!}
    {!! Form::text('title', old('title'), ['class' => 'form-control required']) !!}
  </div>
</div>
@endif

resources/views/admin/construction/create.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::open(['method' => 'POST', 'role' => 'form', 'class' => 'form', 'route' => 'adm.cons.store', 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Novo Post</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados pessoais
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.construction._form')

              <a href="{{ route('adm.cons.index') }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/construction/edit.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::model($data, ['method' => 'POST', 'role' => 'form', 'class' => 'form', 'route' => ['adm.cons.update', $data->id], 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Editar Post</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados pessoais
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.construction._form')

              <a href="{{ route('adm.cons.index') }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/construction/folders.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Obras</h1>
      <div class="section-header-button mr-2">
        <a href="{{ route('adm.cons.index') }}" class="btn btn-danger btn-icon btn-lg" title="Adicionar"> <i class="fas fa-arrow-left"></i> Voltar</a>
        <a href="{{ route('adm.cons.create') }}" class="btn btn-success btn-icon btn-lg btn-success" title="Adicionar"> <i class="fas fa-plus"></i> Adicionar</a>
      </div>
  </div>

  <div class="section-body">
    <div class="row mt-4">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>
              <i class="far fa-user lga"></i>
              Listagem <br>
              <small>{{ $data->total() }} resultados.</small>
            </h4>
          </div>
          <div class="card-body -table">
            <div class="table-responsive">
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>#</th>
                    <th>Imagem</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($data as $d)
                    <tr>
                      <td>{{ $d->id }}</td>
                      <td>@if($d->img) <img src="{{url('storage/cons/'.$d->img)}}" width="50px" style="margin-bottom: 5px;"> @endif</td>
                      {!! Form::open(['route' => ['adm.cons.destroy', $d->id]]) !!}
                      <td class="no-wrap">
                        <a href="{{ route('adm.cons.show', $d->id) }}" class="btn btn-success">Editar</a> |
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Essa ação não pode ser desfeita!')">Apagar</button>
                      </td>
                      {!! Form::close() !!}
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer">
            <div class="float-right">
              <nav>
                {!! $data->render() !!}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/admin/construction/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Obras</h1>
      <div class="section-header-button mr-2">
        <a href="{{ route('adm.cons.create') }}" class="btn btn-success btn-icon btn-lg btn-success" title="Adicionar"> <i class="fas fa-plus"></i> Adicionar</a>
      </div>
  </div>

  <div class="section-body">
    <div class="row mt-4">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>
              <i class="far fa-user lga"></i>
              Listagem <br>
              <small>{{ $data->total() }} resultados.</small>
            </h4>
          </div>
          <div class="card-body -table">
            <div class="table-responsive">
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>Pasta</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($data as $d)
                    <tr>
                      <td>{{ $d->month_txt. ' / '.$d->year }}</td>
                      <td class="no-wrap">
                        <a href="{{ route('adm.cons.folder', [$d->month, $d->year]) }}" class="btn btn-success">Fotos</a>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer">
            <div class="float-right">
              <nav>
                {!! $data->render() !!}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection