routes/web.php
<?php

Route::name('index')->get('/', 'HomeController@index');
Route::name('terms')->get('/terms', 'HomeController@terms');
Route::name('contact')->post('contact', 'ContactController@store');
Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
Auth::routes(['register' => false]);

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@panel')->name('panel');

    Route::prefix('home')->name('home.')->group(function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('create', 'AdminController@create')->name('create');
        Route::post('create', 'AdminController@store')->name('store');
        Route::post('{id}/delete', 'AdminController@destroy')->name('destroy');
        Route::get('{id}', 'AdminController@show')->name('show');
        Route::post('{id}', 'AdminController@update')->name('update');
    });

    Route::prefix('home2')->name('home2.')->group(function () {
        Route::get('/', 'HomeController@admin')->name('index');
        Route::get('create', 'HomeController@create')->name('create');
        Route::post('create', 'HomeController@store')->name('store');
        Route::post('{id}/delete', 'HomeController@destroy')->name('destroy');
        Route::get('{id}', 'HomeController@show')->name('show');
        Route::post('{id}', 'HomeController@update')->name('update');

        Route::get('{home}/photos/', 'HomePhotoController@index')->name('photo.index');
        Route::get('{home}/photos/create', 'HomePhotoController@create')->name('photo.create');
        Route::post('{home}/photos/create', 'HomePhotoController@store')->name('photo.store');
        Route::post('{home}/photos/{id}/delete', 'HomePhotoController@destroy')->name('photo.destroy');
        Route::get('{home}/photos/{id}', 'HomePhotoController@show')->name('photo.show');
        Route::post('{home}/photos/{id}', 'HomePhotoController@update')->name('photo.update');
    });

    Route::prefix('obras')->name('cons.')->group(function () {
        Route::get('/', 'ConsController@index')->name('index');
        Route::get('create', 'ConsController@create')->name('create');
        Route::post('create', 'ConsController@store')->name('store');
        Route::post('{id}/delete', 'ConsController@destroy')->name('destroy');
        Route::get('{id}', 'ConsController@show')->name('show');
        Route::post('{id}', 'ConsController@update')->name('update');
        Route::get('{month}/{year}', 'ConsController@folder')->name('folder');
    });

    Route::prefix('contatos')->name('contact.')->group(function () {
        Route::get('/', 'ContactController@index')->name('index');
    });

    Route::prefix('fale-conosco')->name('support.')->group(function () {
        Route::get('/{pp?}', 'SupportController@show')->name('show');
        Route::post('/', 'SupportController@update')->name('update');
    });

});

resources/views/admin/partials/_ckeditor.blade.php
@section('scripts')
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>

<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };
  CKEDITOR.replace({{$id}}, options);
</script>
@endsection

resources/views/admin/partials/_icons.blade.php
<div class="icon-holder">
    <div id="icons-wrapper">
        <section>
            <ul>
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-cross', old($name), ['class' => 'custom-control-input', 'id' => $name.'-1']) !!}
                        <label class="custom-control-label" for="{{$name}}-1">
                            <i class="icon icon-cross"></i>
                            <p>icon-cross</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-phone', old($name), ['class' => 'custom-control-input', 'id' => $name.'-2']) !!}
                        <label class="custom-control-label" for="{{$name}}-2">
                            <i class="icon icon-phone"></i>
                            <p>icon-phone</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-bars', old($name), ['class' => 'custom-control-input', 'id' => $name.'-3']) !!}
                        <label class="custom-control-label" for="{{$name}}-3">
                            <i class="icon icon-bars"></i>
                            <p>icon-bars</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-mail', old($name), ['class' => 'custom-control-input', 'id' => $name.'-4']) !!}
                        <label class="custom-control-label" for="{{$name}}-4">
                            <i class="icon icon-mail"></i>
                            <p>icon-mail</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-zoom', old($name), ['class' => 'custom-control-input', 'id' => $name.'-5']) !!}
                        <label class="custom-control-label" for="{{$name}}-5">
                            <i class="icon icon-zoom"></i>
                            <p>icon-zoom</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-whats', old($name), ['class' => 'custom-control-input', 'id' => $name.'-6']) !!}
                        <label class="custom-control-label" for="{{$name}}-6">
                            <i class="icon icon-whats"></i>
                            <p>icon-whats</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-plane', old($name), ['class' => 'custom-control-input', 'id' => $name.'-7']) !!}
                        <label class="custom-control-label" for="{{$name}}-7">
                            <i class="icon icon-plane"></i>
                            <p>icon-plane</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-insta', old($name), ['class' => 'custom-control-input', 'id' => $name.'-8']) !!}
                        <label class="custom-control-label" for="{{$name}}-8">
                            <i class="icon icon-insta"></i>
                            <p>icon-insta</p>
                        </label>
                    </div>
                </li>
            
                <li>
                    <div class="custom-control custom-radio">
                        {!! Form::radio($name, 'icon-download', old($name), ['class' => 'custom-control-input', 'id' => $name.'-9']) !!}
                        <label class="custom-control-label" for="{{$name}}-9">
                            <i class="icon icon-download"></i>
                            <p>icon-download</p>
                    </label>
                    </div>
                </li>
            
            <!-- list of icons here with the proper class-->
            </ul>
        </section>
    </div>
</div>

@push('scripts_custom')
    <script>
        function setCollapse(id) {
            $('#'+id.id).collapse('toggle');
        }
    </script>
@endpush

resources/views/admin/partials/_maskmoney.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>

<script>
  $(function() {
    $('#currency').maskMoney({prefix:'R$ ', allowNegative: true, thousands:'.', decimal:',', affixesStay: false});
    @if(isset($data))
        $("#currency").focus();
    @endif
  });
</script>

resources/views/admin/partials/breadcrumbs.blade.php
@if(Agent::isDesktop())
@if (count($breadcrumbs))
  <div class="section-header-breadcrumb">
    @foreach ($breadcrumbs as $breadcrumb)
      @if ($breadcrumb->url && !$loop->last)
        <div class="breadcrumb-item">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @else
        <div class="breadcrumb-item breadcrumb-active">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @endif
    @endforeach
  </div>
@endif
@endif

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
  <div class="footer-left">
    Copyright &copy; {{date('Y')}}
    <div class="bullet"></div> Desenvolvido e mantido por  <a href="https://qualitare.com/">Qualitare</a>
  </div>
  <div class="footer-right">
    1.0.0
  </div>
</footer>

resources/views/admin/partials/nav.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
    </ul>
  </form>
  <ul class="navbar-nav navbar-right">
    @auth()
    <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
      <div class="d-sm-none d-lg-inline-block">Olá, {{ auth()->user()->name }}</div></a>
      {!! Form::open(['route' => 'logout']) !!}
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-divider"></div>
        <button type="submit" class="dropdown-item has-icon text-danger">
          <i class="fas fa-sign-out-alt"></i> Logout
        </button>
      </div>
      {!! Form::close() !!}
    </li>
    @endauth
  </ul>
</nav>

resources/views/admin/partials/placeable.blade.php
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4>Endereço</h4>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-12 col-md-3">
            <div class="form-group mb-4">
              {!! Form::hidden('address[id]', isset($result->placeable) ? $result->placeable->id : null) !!}
              {!! Form::label('address[cep]', 'CEP', ['class' => '']) !!}
              {!! Form::text('address[cep]', isset($result->placeable) ? $result->placeable->cep : old('address[cep]'), ['class' => 'form-control js-mask-cep', 'id' => 'cep']) !!}
              @if($errors->has('address.cep'))
                <span class="text-danger">{{ $errors->first('address.cep') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-9">
            <div class="form-group mb-4">
              {!! Form::label('address[street]', 'Rua', ['class' => '']) !!}
              {!! Form::text('address[street]', isset($result->placeable) ? $result->placeable->street : old('address[street]'), ['class' => 'form-control', 'id' => 'rua']) !!}
              @if($errors->has('address.street'))
                <span class="text-danger">{{ $errors->first('address.street') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-5">
            <div class="form-group mb-4">
              {!! Form::label('address[neighborhood]', 'Bairro', ['class' => '']) !!}
              {!! Form::text('address[neighborhood]', isset($result->placeable) ? $result->placeable->neighborhood : old('address[neighborhood]'), ['class' => 'form-control', 'id' => 'bairro']) !!}
              @if($errors->has('address.neighborhood'))
                <span class="text-danger">{{ $errors->first('address.neighborhood') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-5">
            <div class="form-group mb-4">
              {!! Form::label('address[complement]', 'Complemento', ['class' => '']) !!}
              {!! Form::text('address[complement]', isset($result->placeable) ? $result->placeable->complement : old('address[complement]'), ['class' => 'form-control']) !!}
              @if($errors->has('address.complement'))
                <span class="text-danger">{{ $errors->first('address.complement') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-2">
            <div class="form-group mb-4">
              {!! Form::label('address[number]', 'Número', ['class' => '']) !!}
              {!! Form::text('address[number]', isset($result->placeable) ? $result->placeable->number : old('address[number]'), ['class' => 'form-control']) !!}
              @if($errors->has('address.number'))
                <span class="text-danger">{{ $errors->first('address.number') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-3">
            <div class="form-group mb-4">
              {!! Form::label('address[city]', 'Cidade', ['class' => '']) !!}
              {!! Form::text('address[city]', isset($result->placeable) ? $result->placeable->city : old('address[city]'), ['class' => 'form-control', 'id' => 'localidade']) !!}
              @if($errors->has('address.city'))
                <span class="text-danger">{{ $errors->first('address.city') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-2">
            <div class="form-group mb-4">
              {!! Form::label('address[state]', 'Estado', ['class' => '']) !!}
              {!! Form::text('address[state]', isset($result->placeable) ? $result->placeable->state : old('address[state]'), ['class' => 'form-control', 'id' => 'uf']) !!}
              @if($errors->has('address.state'))
                <span class="text-danger">{{ $errors->first('address.state') }}</span>
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/partials/scripts.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js"></script>

<script src="{{ asset('/assets/js/mask.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/pt.js"></script>


<script src="{{ asset('/assets/js/stisla.js') }}"></script>
<!-- JS Libraies -->

<!-- Template JS File -->
<script src="{{ asset('/assets/js-duallistbox/jquery.bootstrap-duallistbox.js') }}"></script>
<script src="{{ asset('/assets/js/scripts.js') }}"></script>
<script src="{{ asset('/assets/js/custom.js') }}"></script>
<script src="{{ asset('/assets/js/cep.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.26.14/sweetalert2.all.min.js"></script>
<script src="{{ asset('/assets/js/admin.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.js"></script>
<script src="{{ asset('/assets/js/sortable.js') }}"></script>

resources/views/admin/partials/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand mb-2">
      <a href="{{ route('adm.panel') }}"><img src="{{ asset('/assets/img/brand.svg') }}" width="50"></a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="{{ route('adm.panel') }}"><img src="{{ asset('/assets/img/brand.svg') }}" width="50"></a>
    </div>
    <ul class="sidebar-menu">
      <li class="menu-header"></li>
      <li class="menu-header">Módulos</li>
      <li class="dropdown ">
        <a href="#" class="nav-link has-dropdown">
          <i class=" far fa-star lga"></i>
          <span>Home</span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <!--<li>
            <a class=" nav-link" href="route('adm.home.index')" title="Leads">Destaques</a>
          </li> -->
          <li>
            <a class=" nav-link" href="{{route('adm.home2.index')}}" title="Leads">Informações</a>
          </li>
          <li>
            <a class=" nav-link" href="{{route('adm.support.show')}}" title="Leads">Fale conosco</a>
          </li>
          <li>
            <a class=" nav-link" href="{{route('adm.support.show', 'pp')}}" title="Leads">Política de Privacidade</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="{{ route('adm.cons.index')}}">
          <i class="far fa-star lga"></i>
          <span>Obras</span>
        </a>
      </li>
      <li>
        <a href="{{ route('adm.contact.index')}}">
          <i class="far fa-star lga"></i>
          <span>Contatos</span>
        </a>
      </li>
    </ul>
  </aside>
</div>

resources/views/admin/partials/styles.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="{{ asset('/assets/modules/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/modules/fontawesome/css/all.min.css') }}">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('/assets/css/style.css') }}?ver=3.0">
<link rel="stylesheet" href="{{ asset('assets_front/icons_font/css/style.css') }}?ver=3.0">
<link rel="stylesheet" href="{{ asset('/assets/css/components.css') }}?ver=3.0">
<link rel="stylesheet" href="{{ asset('/assets/css/custom.css') }}?ver=3.0">
<link rel="stylesheet" href="{{ asset('/assets/js-duallistbox/bootstrap-duallistbox.min.css') }}">